### ISSUE TITLE
Clay pretrained model hugging face URL not found

### ISSUE THREAD

**Issue by patriksabol** [IBM/terratorch#303]
```bashINFO:timm.models._builder:Loading pretrained weights from Hugging Face hub (('made-with-clay/Clay', 'clay-v1-base.ckpt'))
Traceback (most recent call last):
  File "/home/patrik/miniconda/envs/terratorch/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 406, in hf_raise_for_status
    response.raise_for_status()
  File "/home/patrik/miniconda/envs/terratorch/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/made-with-clay/Clay/resolve/main/clay-v1-base.ckpt
```

**Comment by Joao-L-S-Almeida** [comment]
Hi, @patriksabol Have you tested after the inclusion of  #298 ? It should solve the issue.

**Comment by patriksabol** [comment]
Thanks, that worked after ```pip install --upgrade git+https://github.com/IBM/terratorch.git```
